### ISSUE TITLE
Sign in with github

### ISSUE THREAD

**Issue by iemejia** [igrigorik/vimgolf#119]
Hello,
I would like to know if you plan to support other authentication schemas, in particular authentication via github since it's the 'logical' authentication environment for vim users (more than twitter IMHO).
Thanks,
-Ismael

**Comment by ecbrodie** [comment]
@igrigorik are you willing to reconsider this? I would love to participate in vimgolf, but I do not do any social networking and therefore I do not have a Twitter account.

Github as an SSO/auth source makes a lot of sense. Most people who use VIM or Ruby will have at least some experience with software development and therefore most likely have a Github account. I can only imagine how the usage of vimgolf will go through the roof with Github auth, even way beyond the usage numbers you experience from just Twitter users 😃 

If you do not have any interest or energy in implementing this yourself, are you open to a community contribution to support this? I'd love to take a stab at this.

**Comment by igrigorik** [comment]
@ecbrodie I've heard a few requests for GH auth over the years, but not that many.. I could be wrong, but I don't expect a wave of users if we were to unlock this. That said, yes, I would be willing to accept a PR if it's able to provide all the right/same features as current twitter profiles.

**Comment by Karmaki** [comment]
I know some peuple who do not want to have a Twitter account, ever, but are interested in using vimgolf. So I think a Github auth would be a really good idea!

**Comment by Hettomei** [comment]
+1 if anybody want to code this feature :)
