### ISSUE TITLE
Unable to golf

### ISSUE THREAD

**Issue by vito-c** [igrigorik/vimgolf#124]
I was going to play a couple rounds of golf but couldn't make it out on the course for some reason :(

> vimgolf put 524e1a20b81fe50002000008
> Downloading Vimgolf challenge: 524e1a20b81fe50002000008
> Uh oh, something went wrong! Error: Uh oh, couldn't download or parse challenge, please verify your challenge id & client version.
> If the error persists, please report it to github.com/igrigorik/vimgolf

**Comment by jaapie** [comment]
I had this problem. I found that `http://www.vimgolf.com` was down and I had to prepend `GOLFHOST=http://vimgolf.com` to get my challenge downloaded.
