### ISSUE TITLE
Player pages show wrong rank

### ISSUE THREAD

**Issue by urticadioica** [igrigorik/vimgolf#141]
When you see someone get first place on a challenge with 100 people, you expect to see "Rank: 1/100" on their player page, right? That's how it used to be. I first noticed it wasn't several months ago (sorry).

More specifically, the people with the same score are always grouped together, but their ranks are shuffled, rather than the tie being broken by date. Here's an example from [Just the middle](http://www.vimgolf.com/challenges/54862fbb3f90ac0002904cf5), with the proper rank of the "Score: 7"s and their rank on the player page:

| Actual rank | Player page |
| --- | --- |
| 1 | 17 |
| 2 | 15 |
| 3 | 14 |
| 4 | 12 |
| 5 | 10 |
| 6 | 9 |
| 7 | 8 |
| 8 | 5 |
| 9 | 2 |
| 10 | 3 |
| 11 | 4 |
| 12 | 11 |
| 13 | 18 |
| 14 | 19 |
| 15 | 16 |
| 16 | 13 |
| 17 | 7 |
| 18 | 6 |
| 19 | 1 |

**Comment by filbranden** [comment]
Possibly related: #293

Though I can't confirm, since this issue is over 5 years old...

**Comment by filbranden** [comment]
I'll assume this is fixed now.
