### ISSUE TITLE
E45 readonly  option is set - add ! to override

### ISSUE THREAD

**Issue by zuloloxi** [igrigorik/vimgolf#143]
Hi, 
With CLI 0.4.7, I have the message: E45: 'readonly' option is set (add ! to override) , when exit from vim with ZZ, to send the solution...  
Details for:
-platform windows 7 64
-vim 7.4.552 win32 console 
-RubyInstaller ruby-2.0.0-p598-86 (win32)
These worked well with CLI 0.4.6

**Comment by urticadioica** [comment]
I messed up. #144 should fix this, I hope. If @zuloloxi could confirm this works right, that would be great.

**Comment by igrigorik** [comment]
@zuloloxi can you give it a try on your end before we push a new release?

```bash
$> git clone https://github.com/igrigorik/vimgolf.git
$> cd vimgolf
$> ./bin/vimgolf put ...
```

That (or something close to it) should do the trick...

**Comment by zuloloxi** [comment]
It works
vimgolf put 5192f96ad8df110002000002
Downloading Vimgolf challenge: 5192f96ad8df110002000002
Launching VimGolf session for challenge: 5192f96ad8df110002000002

Here are your keystrokes:
cw(<C-R><C-P>-)<Esc>W.W.ZZ

Success! Your output matches. Your score: 14
[w] Upload result and retry the challenge
[x] Upload result and quit
[r] Do not upload result and retry the challenge
[q] Do not upload result and quit
Choice> w
Uploading to VimGolf...
Uploaded entry.

**Comment by igrigorik** [comment]
0.4.8 is out with the bugfix.

**Comment by zuloloxi** [comment]
Now, tested CLI 0.4.8, it's working nice, and nice features ! Great job !
