### ISSUE TITLE
Windows CTRL-Z Cheat

### ISSUE THREAD

**Issue by dsewtz** [igrigorik/vimgolf#147]
I joined Twitter just to play vimgolf and inadvertently cheated in one of my first submissions:
- After I had worked through the ranks to discover "ZZ" instead of :wq
- I accidentally pressed <CTRL-ZZ> instead of <SHIFT-ZZ>
- and expected the result to be worse than before
- instead it was better by a count of 2 

-> On Windows 7 in cmd or MSYS <CTRL-ZZ> <SHIFT-ZZ> removes the last/next two keystrokes from the count (Here are your keytrokes: "...<ESC>" , line ends with ESC, ZZ is missing).

At first I thought that I had an old gem, because you mention a windows bugfix with 0.4.8, but these are my versions:
ruby: 2.1.5p273   gem:2.2.2   vimgolf:0.4.8

**Comment by urticadioica** [comment]
Let's see if I understand. You try to enter a solution like `ihello<Esc>ZZ`. You type `<C-Z>` instead of `Z` on accident. What happens next? Does vim get suspended? Or do you continue to type `ZZ` afterward?

If you run `vim -Z` from the command line and hit `<C-Z>`, do you get a message like "E145: Shell commands not allowed in rvim"?

**Comment by dsewtz** [comment]
Okay, i did a little more testing:
- I see the message "E145:..." when i hit `<C-Z>`
- After `<C-Z>` no more keystrokes are recorded

- `<C-Z>ihello<ESC>ZZ` becomes `` (nothing) with a count of 0
If i try to upload a 0-score, I get a message "You are not cheating, are you?"

- `ihello<ESC><C-Z><C-Z>ZZ` becomes `ihello<ESC>` with a count of 7
I tried to upload such a solution for "Just the middle" and it worked. I'm at the top with 6 edits now, please delete that entry, if you find the time :-/ SORRY!
My actual keytrokes where `2D3j3D<C-Z>ZZ`
Here is the output:
>Launching VimGolf session for challenge: 54862fbb3f90ac0002904cf5
>
>Here are your keystrokes:
>2D3j3D
>
>Success! Your output matches. Your score: 6
>[w] Upload result and retry the challenge
>[x] Upload result and quit
>[r] Do not upload result and retry the challenge
>[q] Do not upload result and quit
>Choice> x
>Uploading to VimGolf...
>Uploaded entry.
>View the leaderboard: http://www.vimgolf.com/challenges/54862fbb3f90ac0002904cf5
>
>Thanks for playing`

**Comment by urticadioica** [comment]
@dsewtz #148 should fix the problem for you. I've seen occasional solutions with problems like you'd described before (with the end chopped off). They might have had the same problem. But I never knew where to look before you reported it. It's rare enough, the bug just sat there for a few years.

**Comment by igrigorik** [comment]
Should be resolved via #148. Please reopen if this still an issue.
