### ISSUE TITLE
I can see higher scores than my own

### ISSUE THREAD

**Issue by erf** [igrigorik/vimgolf#149]
I just tried vimgolf for the first time and i scored an 8 on "Just the middle" but i am able to see 7 score solutions.. I don't want to be able to cheat.

**Comment by igrigorik** [comment]
This is intentional. We allow you to peek ahead such that if you're stuck, you can at least iterate through solutions of those ahead of you and get to the top. The goal of vimgolf is to help people learn vim, not to "win" at it :)

**Comment by erf** [comment]
ah ok=)

**Comment by urticadioica** [comment]
> We *force* you to peek ahead...

FTFY. And you missed the other part:

> We keep the best solutions shrouded in mystery. Only those who make a Twitter account, install the client, get a key, and copy hundreds of sub-optimal solutions can discover the secrets of Vimgolf.
