### ISSUE TITLE
I am rank #18 but the highest rank answer I can see is #20

### ISSUE THREAD

**Issue by dechimp** [igrigorik/vimgolf#154]
I cannot see solutions from other players near my score. If I have a score of 31, shouldn't I be able to see answers with score 30 or above? 

@USDollarPrice is me

![image](https://cloud.githubusercontent.com/assets/746711/6543962/0d1549a2-c4ec-11e4-9b21-3c20d29da5de.png)
![image](https://cloud.githubusercontent.com/assets/746711/6543963/170f42d2-c4ec-11e4-8be7-d706e57e2dba.png)

**Comment by igrigorik** [comment]
Hmm, odd.. looks like a bug. Thanks for reporting it, will look into.

**Comment by urticadioica** [comment]
You're logged in, right? You're seeing about what I'd expect if you weren't logged in. Keep in mind that login is separate for vimgolf.com and www.vimgolf.com for some reason.

**Comment by dechimp** [comment]
Yeah I am logged in, otherwise that blue box at the top would tell me to
log in to play

**Comment by dechimp** [comment]
Derp.  I was logged in, but to the wrong account.  Thanks for the help.
