### ISSUE TITLE
  vimgolf put ... "Vim did not exit properly"

### ISSUE THREAD

**Issue by e-monson** [igrigorik/vimgolf#156]
Hi, 
I seem to be having the exact same issue as this: https://github.com/igrigorik/vimgolf/issues/88, but I'm running Fedora 21, with Vim version 7.4. 

GOLFDEBUG=true vimgolf put 524e1a20b81fe50002000008
Downloading Vimgolf challenge: 524e1a20b81fe50002000008
Launching VimGolf session for challenge: 524e1a20b81fe50002000008
["/home/blimpse/.gem/ruby/gems/vimgolf-0.4.8/lib/vimgolf/cli.rb:113:in `play'", ["vim", "-Z", "-n", "--noplugin", "--nofork", "-i", "NONE", "+0", "-u", "/home/blimpse/.gem/ruby/gems/vimgolf-0.4.8/lib/vimgolf/vimgolf.vimrc", "-U", "NONE", "-W", "/tmp/golflog20150501-7189-18x3tof", "/tmp/vimgolf20150501-7189-105ow90.rb"]]
	  Uh oh, Vim did not exit properly.
	  Please ensure you can execute 'Vim' from the commandline.
	  If the problem persists, please report the error on github.com/igrigorik/vimgolf

Like the previous issue, I can run vim with the same arguments and it works fine.

**Comment by e-monson** [comment]
Nevermind. I remembered I had installed gvim and aliased "vim"="gvim -v" to get get clipboard support (which I actually didn't need to do, anyway).

**Comment by zhangzs66** [comment]
When I put a vimgolf, it says Uh oh, Vim did not exit properly. How to deal with this problem? Thank you~!

**Comment by Erhannis** [comment]
On mine (Ubuntu), I had to 1. add `alias vim='vi'` to my ~/.bashrc, and 2. `apt install vim-gui-common`.
