### ISSUE TITLE
Make nav username link to "profile"

### ISSUE THREAD

**Issue by diiaann** [igrigorik/vimgolf#158]
Small feature request?

<img width="986" alt="screen shot 2015-10-13 at 2 29 33 pm" src="https://cloud.githubusercontent.com/assets/721452/10468956/ef33744a-71b6-11e5-8dc6-7118aedb2489.png">

To get to my page, I currently either have to type in the URL or search for my name in the long list and then click on that link.

**Comment by wcpines** [comment]
If I understand the request (and code) correctly, this just requires adding a link in the `navigation` div in [application.html.erb](https://github.com/igrigorik/vimgolf/blob/master/app/views/layouts/application.html.erb#L30).

But I'm seeing that the `user#show` route was commented out a few weeks ago in commit e26e0c07.

@igrigorik is this something that might be addressed in #175?

**Comment by igrigorik** [comment]
Yep, the link fix is trivial. However, we first need to fix the data model.. I disabled user pages to stabilize the site -- see https://github.com/igrigorik/vimgolf/issues/174.

**Comment by wcpines** [comment]
Got it, thanks!

**Comment by igrigorik** [comment]
Closing. Resolved via https://github.com/igrigorik/vimgolf/pull/251.
