### ISSUE TITLE
Not able to run vimgolf put ??

### ISSUE THREAD

**Issue by benbasuni** [igrigorik/vimgolf#159]
Downloading Vimgolf challenge: 1
/Library/Ruby/Gems/2.0.0/gems/vimgolf-0.4.8/lib/vimgolf/challenge.rb:72:in `rescue in download': Uh oh, couldn't download or parse challenge, please verify your challenge id & client version. (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/vimgolf-0.4.8/lib/vimgolf/challenge.rb:40:in `download'
	from /Library/Ruby/Gems/2.0.0/gems/vimgolf-0.4.8/lib/vimgolf/cli.rb:74:in `put'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/vimgolf-0.4.8/lib/vimgolf/cli.rb:32:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/vimgolf-0.4.8/bin/vimgolf:9:in `<top (required)>'
	from /usr/bin/vimgolf:23:in `load'
	from /usr/bin/vimgolf:23:in `<main>'

It's probably something really simple, but I tried rerunning the vimgolf setup and manually typing out my key code. I double checked it to make sure that it was right. Tried browsing around the vimgolf forum to find solutions, but couldn't find one that was specific to mine. 

If someone can help or redirect me that'd be great. THanks!

**Comment by igrigorik** [comment]
Are you sure you're downloading the right ID? From the debug log, it looks like you're trying to fetch "1", whereas a full id is something like "55b18bbea9c2c30d04000001".. i.e. "vimgolf put 55b18bbea9c2c30d04000001".

**Comment by benbasuni** [comment]
i see. where do i find the full id for examples? starting from beginners..? I'm fairly new to the vimgolf community. Thank you igrigorik.

**Comment by igrigorik** [comment]
Open one of the challenges in your browser, and you'll see the command in top right, e.g..

- http://vimgolf.com/challenges/55b18bbea9c2c30d04000001
- vimgolf put 55b18bbea9c2c30d04000001
