### ISSUE TITLE
Repeatedly get "Couldn't download" and "upload has failed"

### ISSUE THREAD

**Issue by KyleLH** [igrigorik/vimgolf#160]
More often than not, when I try to download a challenge or upload a solution, it seems like it can't connect to the server. Probably just a networking issue, but figured I'd at least file an issue since one hasn't been posted yet.

**Comment by igrigorik** [comment]
Hmm... Can you set DEBUG=true in your env? That should output a bit more data about the exception next time it happens.

**Comment by jaapie** [comment]
I've been getting these errors too. Following is the output when `GOLFDEBUG=true`:

```
~ $ GOLFDEBUG=true vimgolf put 55b18bbea9c2c30d04000001
Downloading Vimgolf challenge: 55b18bbea9c2c30d04000001
["/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/vimgolf-0.4.8/lib/vimgolf/challenge.rb:71:in `rescue in download'", #<JSON::ParserError: 757: unexpected token at '<html><body>You are being <a href="http://www.vimgolf.com/">redirected</a>.</body></html>'>]
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/vimgolf-0.4.8/lib/vimgolf/challenge.rb:72:in `rescue in download': Uh oh, couldn't download or parse challenge, please verify your challenge id & client version. (RuntimeError)
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/vimgolf-0.4.8/lib/vimgolf/challenge.rb:40:in `download'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/vimgolf-0.4.8/lib/vimgolf/cli.rb:74:in `put'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/vimgolf-0.4.8/lib/vimgolf/cli.rb:32:in `start'
	from /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/vimgolf-0.4.8/bin/vimgolf:9:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.3/bin/vimgolf:23:in `load'
	from /usr/local/var/rbenv/versions/2.2.3/bin/vimgolf:23:in `<main>'
```

There is a JSON::ParserError because instead of getting JSON back, HTML is returned in the response from the webserver. The HTML is as follows: `<html><body>You are being <a href="http://www.vimgolf.com/">redirected</a>.</body></html>`. That message has come up in the web browser also.

Interestingly, as mentioned in #124, if I prepend `GOLFHOST=http://vimgolf` to the command, it works.

**Comment by igrigorik** [comment]
Hmm, this is odd. The underlying cause, I think, is the unstable runtime performance.. The original (very simple) design of the database has outgrown itself and causing slow responses that occasionally bring down the app server. We need to fix that, and I have a feeling all of these issues will go away.

**Comment by KyleLH** [comment]
I kind of figured it was a scaling issue, just thought I'd let you guys know. Great job with the application though! It's definitely awesome :+1:
