### ISSUE TITLE
Vimgolf setup never finishes

### ISSUE THREAD

**Issue by durgaswaroop** [igrigorik/vimgolf#161]
I am fairly new to Vim and entirely new to Ruby. I managed to install Vimgolf. But, the next step Setup is never getting finished. It asks for the vimgolf key and i've pasted it and after that nothing happens. It is just stuck there. Is there something else I'm supposed to do there? Please let me know.|
Btw, I am on windows.

**Comment by igrigorik** [comment]
Can you walk me through the flow? 
- It prompts you for the key
- You type it in, hit enter
- it hangs?

**Comment by durgaswaroop** [comment]
Hey, @igrigorik . I was trying that on the Git cmd shell. Later i tried it in Powershell and it worked. So, I guess some issues with the Git shell.

**Comment by igrigorik** [comment]
Ok, good, glad it worked!
