### ISSUE TITLE
Downloading/uploading challenges is very slow

### ISSUE THREAD

**Issue by jwgoes** [igrigorik/vimgolf#163]
The site in general seems to run slow on many days, with me needing to refresh pages multiple times to get them to show. But lately, even downloading and uploading challenges can take many minutes. Sometimes it takes so long I have ctrl-C.

I love your site and the idea, I'm learning quite a lot. I would be happy to donate to keep it going.

**Comment by igrigorik** [comment]
Merging with #150.
