### ISSUE TITLE
vimgolf client using ruby 2.2.4 RuntimeError

### ISSUE THREAD

**Issue by zuloloxi** [igrigorik/vimgolf#164]
Hello, 

Vimgolf with ruby installer for windows (32 bits) 2.2.4 give runtime error :

> C:\Users\govim74\Downloads\ruby-2.2.4-i386-mingw32\bin>vimgolf put 571028960c64c90990000003
> Downloading Vimgolf challenge: 571028960c64c90990000003
> C:/Users/govim74/Downloads/ruby-2.2.4-i386-mingw32/lib/ruby/gems/2.2.0/gems/vimgolf-0.4.8/lib/vimgolf/challenge.rb:72:in `rescue in download': Uh oh, couldn't download or parse challenge, please verify your challenge id & client version. (RuntimeError)
>         from C:/Users/govim74/Downloads/ruby-2.2.4-i386-mingw32/lib/ruby/gems/2.2.0/gems/vimgolf-0.4.8/lib/vimgolf/challenge.rb:40:in`download'
>         from C:/Users/govim74/Downloads/ruby-2.2.4-i386-mingw32/lib/ruby/gems/2.2.0/gems/vimgolf-0.4.8/lib/vimgolf/cli.rb:74:in `put'
>         from C:/Users/govim74/Downloads/ruby-2.2.4-i386-mingw32/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
>         from C:/Users/govim74/Downloads/ruby-2.2.4-i386-mingw32/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
>         from C:/Users/govim74/Downloads/ruby-2.2.4-i386-mingw32/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in`dispatch'
>         from C:/Users/govim74/Downloads/ruby-2.2.4-i386-mingw32/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
>         from C:/Users/govim74/Downloads/ruby-2.2.4-i386-mingw32/lib/ruby/gems/2.2.0/gems/vimgolf-0.4.8/lib/vimgolf/cli.rb:32:in`start'
>         from C:/Users/govim74/Downloads/ruby-2.2.4-i386-mingw32/lib/ruby/gems/2.2.0/gems/vimgolf-0.4.8/bin/vimgolf:9:in `<top (required)>'
>         from C:/Users/govim74/Downloads/ruby-2.2.4-i386-mingw32/bin/vimgolf:23:in`load'
>         from C:/Users/govim74/Downloads/ruby-2.2.4-i386-mingw32/bin/vimgolf:23:in `<main>'
> 
> C:\Users\govim74\Downloads\ruby-2.2.4-i386-mingw32\bin> 
> 
> but **Ruby 2.0.0-p648** for windows (32 bits) - http://rubyinstaller.org/downloads/ - **works** nice !

**Comment by igrigorik** [comment]
Please reopen if this is still a problem.

**Comment by zuloloxi** [comment]
I re-tested vimgolf client 0.4.8 with rubyinstaller 2.3.3 32bits on Windows 7 sp1, works also nice !
```
C:\Users\Downloads\uvim\ruby-2.3.3-i386-mingw32\bin>gem install vimgolf
Fetching: thor-0.19.4.gem (100%)
Successfully installed thor-0.19.4
Fetching: json_pure-2.1.0.gem (100%)
Successfully installed json_pure-2.1.0
Fetching: highline-1.7.8.gem (100%)
Successfully installed highline-1.7.8
Fetching: vimgolf-0.4.8.gem (100%)

------------------------------------------------------------------------------
Thank you for installing vimgolf-0.4.8.

0.1.3: custom vimgolf .vimrc file to help level the playing field
0.2.0: proxy support, custom diffs + proper vimscript parser/scoring
0.3.0: improve windows support, switch to YAML to remove c-ext dependency
0.4.0: improved diff/retry CLI, emacs support: http://bit.ly/yHgOPF

*NOTE*: please re-run "vimgolf setup" prior to playing!

For more information, rules & updates: http://vimgolf.com/about
------------------------------------------------------------------------------
Successfully installed vimgolf-0.4.8
Parsing documentation for thor-0.19.4
Installing ri documentation for thor-0.19.4
Parsing documentation for json_pure-2.1.0
Installing ri documentation for json_pure-2.1.0
Parsing documentation for highline-1.7.8
Installing ri documentation for highline-1.7.8
Parsing documentation for vimgolf-0.4.8
Installing ri documentation for vimgolf-0.4.8
Done installing documentation for thor, json_pure, highline, vimgolf after 9 seconds
4 gems installed
...
C:\Users\uvim\Downloads\ruby-2.3.3-i386-mingw32\bin>vimgolf put 59265921e633730ce0000016
Downloading Vimgolf challenge: 59265921e633730ce0000016
Launching VimGolf session for challenge: 59265921e633730ce0000016

Here are your keystrokes:
G<C-V>2k2lxHPZZ
...
```
