### ISSUE TITLE
"Attention Required! | CloudFlare" page on downloading a challenge

### ISSUE THREAD

**Issue by subhash-shah** [igrigorik/vimgolf#166]
When I execute `vimgolf put [challenge_id]`, it gave me error **/home/subhash/.rvm/gems/ruby-2.3.0@rails425/gems/vimgolf-0.4.8/lib/vimgolf/challenge.rb:72:in `rescue in download': Uh oh, couldn't download or parse challenge, please verify your challenge id & client version. (RuntimeError)**.

I debugged it with `GOLFDEBUG=true vimgolf put [challenge_id]` and I got that instead of JSON data, it was rendering **"Attention Required!"** HTML page.

I am not sure if this issue belong here but it would be great if someone can help with a work around.

**Comment by igrigorik** [comment]
This is related to https://github.com/igrigorik/vimgolf/issues/150 :(
