### ISSUE TITLE
:wq<CR> counted in my result

### ISSUE THREAD

**Issue by daniels** [igrigorik/vimgolf#168]
I've just completed my first [challenge](http://www.vimgolf.com/challenges/56d70389bbbe462aff01d42a). I used 13 keystrokes to finish the work, and then I had to(?) save and quit to submit the result. But then `:wq<CR>` was displayed as part of my keystrokes and my score was shown as 17. I see the same on some of the solutions on the web site, but most of them are just the editing commands.

How do I finish a challenge so that saving and quitting isn't counted?

**Comment by urticadioica** [comment]
Save and quit is *supposed to* count. That's part of the rules. Most players do it with `ZZ` however, so they don't waste so many strokes (`:help ZZ`).

*Almost* every perfect solution ends in `ZZ`, but a few don't. Tactically it's still interesting.

**Comment by daniels** [comment]
Oh, then I learned something new on my first challenge! Thanks!
