### ISSUE TITLE
Not working from Russia

### ISSUE THREAD

**Issue by mrvlasyuk** [igrigorik/vimgolf#169]
I did a little research and found out the reason. Vimgolf has the same cloudflare IPs as some web-casino blocked in Russia. Is it possible to fix this?

**Comment by igrigorik** [comment]
Sigh, that's unfortunate.. VimGolf is fronted by CloudFlare, so my guess is that all (or some significant subset) of their IPs will be blocked. But, that also means that most other CF-hosted sites would be inaccessible too? Can you try opening https://istlsfastyet.com/, does that work?

**Comment by mrvlasyuk** [comment]
https://istlsfastyet.com/ is working fine. I didn't notice any problems with other sites hosted by CF before.

As you can see from the links below vimgolf has same CF IPs with https://www.dasistcasino.com/. There are only 2 IPs blocked, not the whole subset.
https://reestr.rublacklist.net/search/?q=104.28.11.41
https://reestr.rublacklist.net/search/?q=104.28.10.41

**Comment by mrvlasyuk** [comment]
Maybe there's a way to change current IP or add a new IP address?

**Comment by igrigorik** [comment]
Filed a bug with CloudFlare.. stay tuned.

**Comment by mrvlasyuk** [comment]
http://www.vimgolf.com/ is working now. Pages load slowly, but it works! gem vimgolf also works fine. Thanks a lot!

**Comment by igrigorik** [comment]
👍
