### ISSUE TITLE
Disable system clipboard in vimrc

### ISSUE THREAD

**Issue by popeye123** [igrigorik/vimgolf#170]
With copy/pasting from the system clipboard, every challenge can be solved with very few keystrokes. To prevent this the clipboard should be disabled in the vimrc. I found that the problem was already reported in the closed, but unresolved issue #22.

I found following post on [stackoverflow](https://stackoverflow.com/questions/17402020/how-to-disable-clipboard-in-vim), which suggests putting `set clipboard=exclude:.*` in the vimrc. The proposed solution worked for me.

**Comment by igrigorik** [comment]
@urticadioica wdyt? any objections?

**Comment by urticadioica** [comment]
There's a rare, (semi-)legit tactic that actually uses the clipboard. If you take advantage of the fact that using visual mode puts selected text into the X clipboard (in X gvim or in terminal with `+xterm_clipboard`), you can `"*p` to paste that text without explicitly yanking it. This can save a stroke in cases where you need to do some non-yanking thing in visual mode, and reselecting the area to yank would be slower than the overhead of specifying an alternate register.

I wrote [a challenge](http://www.vimgolf.com/challenges/5447b459380e8b0002000db3) a couple years ago that forces you to take advantage of this in a pretty naive way, using the `r` command to force the visual area. It's a stupid challenge, so I'm not attached to it. On [Chinese Multiplication Table](https://www.vimgolf.com/challenges/510b1c61e48b7e0002000028) you'll see a more natural setting, where setting up a visual increment defines the area.

Note that this doesn't work by default in Windows. Read `:help 'guioptions'` and you'll see the missing `a` flag in the Windows defaults. Setting it explicitly, one way or the other, would (should) make the platforms more consistent.

As for preventing cheats, that would be nice, and I'd agree with the proposal no hesitation if there weren't an interesting tactic it would wipe out. But ultimately, there's no way to prevent cheats short of server-side verification. What would really help help catch cheaters quickly is a recent solution page, either showing all recent solutions (though the volume might be too high), or just new first place entries. If there's a new first place, either we've got a cheater, or someone has found something really cool. Either way I want to know. (It's a bit disappointing when I don't see a new discovery until months later.) Now that everyone's helping work on the server, this would be my top wishlist item.

@popeye123 I'm asking really late, but was there a cheat you saw that brought this up? If I know where it is, I can delete it right away. (With the size of the site and the slowness of page loads on the biggest challenges, it's hard to catch everything these days.)

**Comment by igrigorik** [comment]
@urticadioica +1 for moderation workflow, opened a new issue to track it (https://github.com/igrigorik/vimgolf/issues/183). 

With that, it sounds like we want to keep clipboard around. Closing. Feel free to reopen if anyone feels strongly otherwise.

**Comment by popeye123** [comment]
@urticadioica Yes, the current top entry by DatBoi in the [One number per line](http://vimgolf.com/challenges/56fb2e75ccffcc0009026473#5859b8c21eea0757dc04cd4a) challenge brought this up.

**Comment by urticadioica** [comment]
@popeye123  Thanks, I took care of it.
