### ISSUE TITLE
Improve test coverage and infrastructure

### ISSUE THREAD

**Issue by igrigorik** [igrigorik/vimgolf#172]
Discussion in https://github.com/igrigorik/vimgolf/issues/171.

- [x] Setup CI / Travis builds to run existing tests on checkin and pull requests
- [ ] Review and extend test coverage

... what else?

**Comment by zoso10** [comment]
someone with admin privileges will have to get the repo set up with travis. we can add the `master` branch to the blocklist so it will only build web-related branches. also, we'll either have to edit the default command to run the suite or edit the `Rakefile` to make the default command run the suite since by default travis calls `rake`. 

[here](https://travis-ci.com/getting_started)'s the general getting started guide and [here](https://docs.travis-ci.com/user/languages/ruby/)'s the ruby-specific one.

if you don't mind making people as collaborators I don't mind doing the work on that. I'll PR any code changes.

**Comment by igrigorik** [comment]
@zoso10 added you as collaborator :-). Also, we should resolve https://github.com/igrigorik/vimgolf/issues/176 first, It'll make the rest a lot easier.

**Comment by zoso10** [comment]
@igrigorik ah, didn't see #176. good call; I totally agree. it will make things a lot easier :)

**Comment by igrigorik** [comment]
@zoso10 merged, you should be good to go 👍

**Comment by zoso10** [comment]
@igrigorik oops! I misspoke, you'll have to add the project in travis since you're the admin of the project :)

**Comment by hvenables** [comment]
@igrigorik I am assuming we are going to be moving to the new syntax for rspec? As i have just seen vimgolf is still using the old syntax. Happy to update the syntax then extend the coverage if no one else is working on it?

**Comment by igrigorik** [comment]
@hvenables yes, that would be great. Perhaps open a new bug / WIP PR for this and I can assign it to you?

**Comment by zoso10** [comment]
@hvenables @igrigorik I have a branch going (sorry haven't pushed it yet) adding `capybara` and adding some integration specs to test the whole stack. Updating the current syntax in the specs would be super helpful indeed.

**Comment by hvenables** [comment]
@zoso10 I will update the syntax and make a quick pull request. (Transpec gem makes the task a doodle. Hopefully). Then i will wait for your branch to be merged as yeah we def need to add capybara to get a proper spec coverage

**Comment by hvenables** [comment]
@igrigorik @zoso10 I have made a quick pull request to update the syntax. Ill wait for @zoso10 branch before duplicating the work. Then Ill make a new bug / WIP PR which you can assign to me

**Comment by hvenables** [comment]
@zoso10 How is progress coming on the integration specs?

**Comment by zoso10** [comment]
@hvenables good, I was sorta waiting on #186 since it introduces `factory_girl` which imo is a better way to manage test data. but I can go ahead and start opening up PRs for review so we can get some eyes on them. keep a look out later today/tomorrow :)

**Comment by hvenables** [comment]
@zoso10 Just to let you know i have started a branch to write a feature spec for the entries, hopefully you havent already started doing this?

**Comment by zoso10** [comment]
@hvenables awesome! the last 2 weeks have been a little busy for me so i haven't gotten around to adding more test coverage. thank you!

**Comment by zoso10** [comment]
should we close this issue now that we have good coverage and have started upgrading?

**Comment by igrigorik** [comment]
Yep, makes sense. Thanks all!
