### ISSUE TITLE
Repo structure: split branch vs same branch vs separate repos

### ISSUE THREAD

**Issue by igrigorik** [igrigorik/vimgolf#176]
There are two components to vimgolf: 
1. The 'master' branch contains the CLI to fetch and submit challenges + code to parse VIM logs. 
1. The 'web' branch contains the Rails repo that powers the site.
    - The web branch depends on the CLI code, and the two must be released in parallel, because we want to guarantee that both sides use same parsing logic, etc.

Some options for how to move forward:
1. We can keep existing two-branch structure. This works fine -- I think -- but it does have some downsides: it's not obvious when you first open the repo that the web version is in web branch; merging updates is a bit annoying; many GitHub integrations assume 'master' branch is the source of truth.
1. We can split CLI and web into separate repos. To me, the downside is that now we have to separate but related repos that need to be kept in sync. Also, bugs/proposals in one repo often need input from the other repo and contributors. As such, I think this is less than optimal.
1. We can move Rails code into master branch and put CLI code into "lib": everything lives in same branch, Rails accesses the lib directly. We can still release the gem separately from lib. 

I'm leaning towards (3). Curious to hear other's thoughts...

**Comment by stevecrozz** [comment]
Either 2 repos or everything-on-master strikes me as the right approach. I'm not super familiar with this project yet, but if we went with 2 separate repos, what would need to be kept in sync between them?

**Comment by igrigorik** [comment]
Well, at a minimum we have to coordinate releases of the site whenever we push a new version of the CLI gem. More importantly, it's the communication overhead: I'd prefer that we keep bug / feature discussions in same repo; for outside contributors and bug reports it's also easier to find and reason about a single repo -- otherwise, I'm sure we'll end up with CLI reports on the site repo, and vice versa.

**Comment by stevecrozz** [comment]
Yeah, it is annoying to have to push people to other repos when they report bugs in the wrong place.

Trying to understand the process a bit more though, why is it that we have to coordinate releases of the site whenever we push a new version of the CLI? What's the nature of this coupling?

**Comment by igrigorik** [comment]
> Trying to understand the process a bit more though, why is it that we have to coordinate releases of the site whenever we push a new version of the CLI? What's the nature of this coupling?

When you play locally, your keystrokes are recorded by Vim into a temp file, which the CLI then parses, scores, and gives you an option to upload or retry. If you choose to submit, we upload the log file and it's scored once more by the server. The parser is reused across both the CLI and server and we want to make sure that those are kept in sync and that scores always match -- we've updated it in the past and it can affect your scores. Also, we perform a handshake when the log is updated and verify that the CLI is the latest available version, which allows us to keep players up to date.

My suggestion is that we go with (3)... I'll take a run at merging branches. Stay tuned.

**Comment by stevecrozz** [comment]
I like 3 also. Good luck!

**Comment by igrigorik** [comment]
Done! I think everything is ready to go.. https://github.com/igrigorik/vimgolf
