### ISSUE TITLE
Setup Code Climate for code coverage

### ISSUE THREAD

**Issue by nelsonsar** [igrigorik/vimgolf#182]
I already added the codebase in Code Climate but I can't setup code coverage for it. We can use it to track down some issues while we iterate in code. For more info: https://codeclimate.com/github/igrigorik/vimgolf/builds

**Comment by igrigorik** [comment]
What are the missing steps to enable it?

**Comment by nelsonsar** [comment]
AFAIK https://docs.codeclimate.com/docs/setting-up-test-coverage :)

**Comment by igrigorik** [comment]
Added configs, enabled integrations. Should be good to go!
