### ISSUE TITLE
Switch to small avatars

### ISSUE THREAD

**Issue by urticadioica** [igrigorik/vimgolf#189]
Looking at the avatars URL, you'd think we're currently requesting large avatars. Actually, we're using the wrong URL format, so it's just downloading the default size as a fallback. [Here's the correct format.](https://avatars.io/twitter/udioica/small) The small avatars are 48x48, which is exactly the same size we actually show. Switching would save 10s of MB for users on some of the larger challenges.

**Comment by igrigorik** [comment]
Well, that's silly of me.. Great catch! Will go live next time we push the site.
