### ISSUE TITLE
Disable Cloudflare email obfuscation

### ISSUE THREAD

**Issue by urticadioica** [igrigorik/vimgolf#190]
When you look at the HTML of challenge pages, you'll often find Cloudflare interpreting the text of a solution as an email address, so a snippet like `q9@qZZ` will be replaced by an unwieldy piece of javascript. Makes it awkward to do research on the solution set. :(

[Explanation.](https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-) Looks like there's a widget that can turn it off.

I was wondering if this was the reason Firefox asks me 2-3 times if I want to stop a slow script when I visit the larger pages. After profiling I don't think it's a big factor, but I could be wrong. I know there's something making large pages much slower than they should be in the browser...

**Comment by igrigorik** [comment]
/me shakes head.. 

Disabled. Thanks for reporting this!
