### ISSUE TITLE
High memory use is causing Heroku timeouts

### ISSUE THREAD

**Issue by igrigorik** [igrigorik/vimgolf#206]
![image](https://cloud.githubusercontent.com/assets/10652/26233391/e1a8238a-3c11-11e7-8384-5de432157495.png)

We're eating up memory, which is causing a lot of the stability issues.. Yikes.

**Comment by benoittgt** [comment]
Do you think we could add scout extension? https://elements.heroku.com/addons/scout

And share some result here?

**Comment by igrigorik** [comment]
Installed. Let's let it gather some data..

**Comment by nateberkopec** [comment]
@igrigorik [What's WEB_CONCURRENCY set to on production?](https://github.com/igrigorik/vimgolf/blob/master/config/unicorn.rb#L1)

**Comment by igrigorik** [comment]
@nateberkopec it defaults to 3.

**Comment by igrigorik** [comment]
@benoittgt @nateberkopec happy to add you to Heroku account if you're interested and have bandwidth to dig into it.. just need your email addresses.

**Comment by benoittgt** [comment]
@igrigorik benoit at hopsandfork dot  com

**Comment by nateberkopec** [comment]
I'll let benoit do it - go, my apprentice :D

**Comment by igrigorik** [comment]
@benoittgt invited you and @zoso10. @nateberkopec lmk if you want me to add you.

As a heads up, the prod version is still running the mega-old build. Before we dive too deep into perf, we should get the latest version up and on the latest Heroku stack. Related: https://github.com/igrigorik/vimgolf/pull/217.

**Comment by Hettomei** [comment]
Not sur if High memory use, or just too long request,

But I go in timeout for these 3 case : 
#245 
#244 
#242 

Was because of challenge.save which do one request per entry. (I m pretty sure it is because of validator)

**Comment by igrigorik** [comment]
Resolving, should be addressed by https://github.com/igrigorik/vimgolf/pull/248.
