### ISSUE TITLE
vimgolf doesn't save correct version

### ISSUE THREAD

**Issue by benoittgt** [igrigorik/vimgolf#216]
Hello

In this challenge : http://www.vimgolf.com/challenges/591074530b52f5000c000005
When doing for example this solution `}cL<Esc>M]p8GddZZ`. I get : 

![capture d ecran 2017-06-08 a 19 13 45](https://user-images.githubusercontent.com/8417720/26941399-a4018300-4c7e-11e7-96e4-5f2136e172d9.png)

![capture d ecran 2017-06-08 a 19 13 54](https://user-images.githubusercontent.com/8417720/26941401-a5c13c80-4c7e-11e7-9261-2a8de42b5d1d.png)

Even if I don't have end line..

![capture d ecran 2017-06-08 a 19 13 34](https://user-images.githubusercontent.com/8417720/26941415-b20f4216-4c7e-11e7-9fb5-1f904d814e17.png)

**Comment by urticadioica** [comment]
I'll just leave what I know here. The client is doing the right thing in @benoittgt's case. It's supposed to write that extra newline in the output. It seemed like a few users were *not* getting the extra newline, and that would be a bug if true. But it's hard to tell what their clients are doing without seeing it myself, and I had trouble getting one of them to do more extensive debugging (a bit time-consuming on their part, so I don't blame them).

You can check [the raw json](http://www.vimgolf.com/challenges/591074530b52f5000c000005.json) to confirm the extra newline is correct. It probably would have been ideal if the challenge didn't include it, but that's not what happened. (As a whole, I actually like this challenge. It forces a fairly rare feature in an interesting way.

**Comment by benoittgt** [comment]
Thanks @urticadioica. Do you think it's related to vim version (in my case VIM 8.0 (2016 Sep 12, compiled Jan 12 2017 06:49:50) MacOS X (unix) version Included patches: 1-172) ?

Love to learn vim tips again.

If someone doesn't have the issue with this motion: Ping us. :)
