### ISSUE TITLE
C-Home instead of C-End

### ISSUE THREAD

**Issue by zuloloxi** [igrigorik/vimgolf#220]
For the challenge *Missing Library and a Typo* I used **C-End** keystroke (*Ctrl+End*) to go to the end of buffer, but it is displaying a **C-Home** text in the keystrokes solution  instead.

**Comment by urticadioica** [comment]
This is almost certainly related to #188. The "fix" (if you can call it that) is not in the released vimgolf client. Go ahead and re-open if you think it's something else.

**Comment by zuloloxi** [comment]
Thanks, it's Ok.
For info I cannot re-open, only create new issue.
