### ISSUE TITLE
File autocompletion (<C-x><C-f>) shouldn't allowed

### ISSUE THREAD

**Issue by kutsan** [igrigorik/vimgolf#223]
Recently, I won the "Simple, Practical, and Common" challenge with a score of 16. My solution was `#Yp<C-A>w11<C-A>GO<C-X><C-F><CR><Esc>ZZ`. Creating new file in the same directory and autocompleting that with `<C-x><C-f>` did the work. Obviously it was a cheat and in my opinion it shouldn't allowed to be used. Also, it would be good if you could delete my entry. My username is _kutsankaplan_.

**Comment by voyeg3r** [comment]
I think would be possible to create a temp folder locked or something like that to avoid this technique.

**Comment by kutsan** [comment]
@jk3us Its creator, in this case @oscarmlage, should be able delete their entry.

**Comment by oscarmlage** [comment]
I have to delete the whole challenge, I can not delete just a solution (or I didn't see how to do it).

**Comment by kutsan** [comment]
@oscarmlage According to [this](http://www.vimgolf.com/about) page, it says "Creator of the challenge is also the moderator: can view/delete solutions". I don't know much and how to.

**Comment by Hettomei** [comment]
Occording to the code,
The owner must click on link '6 comments - comment edit' then a div toggle.
Inside the new div, click on delete button

**Comment by oscarmlage** [comment]
Saw it and fixed it. Thanks @Hettomei. I think this issue can be closed.

**Comment by Hettomei** [comment]
To my opinions, this bug can be closed.
Not because the owner can delete entries but because it is currently impossible to solve : 

The only way to detect 'bad pattern' is to run the solution on server's side on a specific configuration.
But vimgolf run on heroku instance. I'm pretty sure we cannot 
- install vim
- run keystroke
- compare file
- insert entry to database if ok

**Comment by Hettomei** [comment]
(I currently discover docker, I am in the mood 'docker all the things' and I m pretty sure we can set a docker that run on both client and server with **-of course- the same configuration** to play vimgolf)
And there is an attempt : https://hub.docker.com/r/kramos/vimgolf/

**Comment by kutsan** [comment]
@oscarmlage Deleting entries one by one is not a solution. We shouldn't close until it's really solved. Also, thanks for deleting their entry. At least, we could do it.

@Hettomei I mean, even basic regex check whether or not input contains `<C-x><C-f>` would be something. I don't think it's impossible to solve.

**Comment by Hettomei** [comment]
@kutsan
Yes maybe a simple solution exist.

But I think regex is not : how do you ensure you are in insert mode and press cx cf ?
There is so various way to achieve a task (that's the point of vimgolf) that it is close to impossible to be confident with a regex

**Comment by kutsan** [comment]
@Hettomei 

> how do you ensure you are in insert mode and press cx cf ?

`<C-x><C-f>` does nothing in other modes, so literally there is no other reason to use them other than in insert mode. I think, no need to unsure that they are in insert mode.

> There is so various way to achieve a task (that's the point of vimgolf) that it is close to impossible to be confident with a regex

I agree but still pressing combination of `<C-x><C-f>` does only filename completion with their default config.

> And I didn't tested it but we can add any content using `r! Bash_command` So a regex for `r!` ?

`:r! command` does produce a lot of keys, I don't think one can win a challenge with reading output of a command. `<C-x><C-f>` works because it's only two keys.

> `<c-r>"! bash_command`

Same problem, a lot of keys. Normal methods would be faster without cheating.

> The good part is that vimgolf is not to win or to be the first, it is to learn, so I m not really sure we should 'fight' 'cheaters' and spend effort on that.

Yeah, I agree but it would be better without cheaters.

Don't worry though, I'm not going to defend regex as a solution here. I don't think we can solve all problems with regex. It was my simplest idea that came to my mind. We need better solutions as you initially suggest.

**Comment by igrigorik** [comment]
Sounds like the resolution here is "wontfix". Closing, but feel free to reopen if there is more to triage and discuss on this one.
