### ISSUE TITLE
Put limits on challenge page for solutions and leader boards

### ISSUE THREAD

**Issue by sagesan** [igrigorik/vimgolf#225]
Please, for the love of god, limit the solution and leader boards count to a sane number (below 500).

I don't think many people actually scroll lower than that, but for popular challenges they get 10000 solutions. And then the page dies because it goes out of memory.

Add 'click to view more' later on, so people can see everything. But put the limit asap. Please.

**Comment by Hettomei** [comment]
Add a reference to #248

**Comment by igrigorik** [comment]
Closing, resolved via above.
