### ISSUE TITLE
I try to run locally, but fail at 'namespace does not exist: vimgolf.challenges'

### ISSUE THREAD

**Issue by Hettomei** [igrigorik/vimgolf#228]
Hi,

Thanks for this game. I learned a lot, and enjoyed to play :)

I tried to run locally in order to submit PR, but I am stuck at the mongodb namespace.

it seems that `rake db:setup` does nothing. Have you already seen this ?

```
MONGODB | localhost:27017 | vimgolf.mapreduce | STARTED | {"mapreduce"=>"challenges", "map"=>"function() { if (this.entries) { emit(this._id, this.entries.length) }}", "reduce"=>"function(k, values) { return values[0]; }", "query"=>{}, "out"=>{:replace=>"count_entries"}}
MONGODB | localhost:27017 | vimgolf.mapreduce | FAILED | namespace does not exist: vimgolf.challenges (26) | 0.002370137s

Mongo::Error::OperationFailure (namespace does not exist: vimgolf.challenges (26)):

app/controllers/main_controller.rb:7:in `find'
app/controllers/main_controller.rb:7:in `each'
app/controllers/main_controller.rb:7:in `to_a'
```

I use ruby 2.4 and mongo client 3.6.3 from https://hub.docker.com/_/mongo/

Here are the steps to come here  (I tried to do a PR, so it is extracted from 'my' README.md): 

# How to contribute

## First installation

You need a ruby installation, same as .ruby-version

I recommend using rbenv, see https://github.com/rbenv/rbenv

```
cd $VIMGOLF_PATH
rbenv install
```

Then you need bundler

```
gem install bundler
```

Then you need all gems to run the apps

```
bundle install
```

You need a mongo-db instance

I recommend docker, see http://pierrepironin.fr/docker-et-mongodb/ for help

```
docker pull mongo
sudo mkdir -p /opt/mongodb/db
docker run -p 27017:27017 -v /opt/mongodb/db:/data/db --name my-mongo-dev -d mongo mongod --auth

db.createUser(
{
user: "siteUserAdmin",
pwd: "unPasswordQuiVaBien",
roles: [{role: "userAdminAnyDatabase", db: "admin"}]
}
)
# ctrl-C

docker exec -it my-mongo-dev mongo 127.0.0.1/vimgolf -u siteUserAdmin -p unPasswordQuiVaBien --authenticationDatabase admin
use vimgolf
db.createUser({
user: "vimgolf",
pwd: "vimgolf",
roles: ["dbOwner"]
})
# ctrl-C
docker exec -it my-mongo-dev mongo 127.0.0.1/vimgolf -u vimgolf -p vimgolf --authenticationDatabase vimgolf
# we are connected
# ctrl-C
```

update config/mongoid.yml with

```
      options:
        user: 'vimgolf'
        password: 'vimgolf'
```

then you need to create the database collection

```
rake db:create_indexes
```

then you are ready to run it locally

```
bundle exec unicorn -c config/unicorn.rb -E development
```

Then open your browser to http://localhost:8080/

If you need more logs, you can

```
tail -f log/development.log
```

**Comment by igrigorik** [comment]
@Hettomei thanks for flagging this! Could have sworn this was working previously. 

- I'd love to see your docs above in our Readme, perhaps as a new section under "how to contribute"?
- Still scratching my head over why db:setup is not doing it's job.

**Comment by Hettomei** [comment]
So : it is not a problem about `rake db:setup`

The problem is only for the lines

```
    @entry_counts = Challenge.count_entries.to_a.inject({}) do |h,v|
      h[v['_id']] = v['value'].to_i
      h
    end
```

removing them and the app run.


Now I need to find an alternative implementation to output entries before pushing a PR.

**Comment by Hettomei** [comment]
By writing some db/seed.rb example, the app run well.
I do other verification and I'll try to push a PR.

Sorry for the inconvenience, I close this issue.

**Comment by igrigorik** [comment]
@Hettomei would love to see+land both your writeup and and the seed.rb fix!
