### ISSUE TITLE
Update project "Modernize vimgolf.com"

### ISSUE THREAD

**Issue by Hettomei** [igrigorik/vimgolf#233]
Hi,

I just discover that you have https://github.com/igrigorik/vimgolf/projects/1 .... I didn't know github has such feature.

I can't see how to update card, for example : 

Move 'task : Add seed file to help starting app locally.' to -> 'done'
Move 'in progress: Improve test coverage and infrastructure' to -> 'done'
Move 'in progress: Make spec suite green' to -> 'done'

**Comment by igrigorik** [comment]
@Hettomei I believe those functions are only open to project admins, which is why you don't see those controls.
