### ISSUE TITLE
"Application Error" on loading http://vimgolf.com/. 

### ISSUE THREAD

**Issue by clonex10100** [igrigorik/vimgolf#235]
I want to play some vimgolf, but whenever I load the website I get a page that says "Application Error." I have tried to load the site on multiple browsers and operating systems.

**Comment by h43z** [comment]
It's definitely down :sob:

**Comment by igrigorik** [comment]
Sorry guys! We should be back up. We hit a limit on the primary DB, so I had to run some compaction and shuffle the replicas — we should back online. 

Now working on landing some upgrades.
