### ISSUE TITLE
Server 500 error when uploading a result

### ISSUE THREAD

**Issue by knightstick** [igrigorik/vimgolf#247]
When trying to complete my first challenge, I got the "Uh oh, entry upload has failed, please check your key." and when I dug in, I found that the server was returning a 500 error.

The form data being sent was:
```
{"challenge_id"=>"55b18bbea9c2c30d04000001", "apikey"=>"[REDACTED]", "entry"=>"6Gyyp\u0001$C11\e3joNew text.\r\e:wq\r"}
```

**Comment by Hettomei** [comment]
I think it is fixed in PR #245

**Comment by Hettomei** [comment]
The PR has been merged. But not pushed to vimgolf. I ping you back when it's done @knightstick

**Comment by Hettomei** [comment]
vimgolf.com is up to date : can you try again and tell me if you see any error when pushing solution ?

I tried with http://vimgolf.com/challenges/55b18bbea9c2c30d04000001 : before I cannot push
after : I can push

**Comment by knightstick** [comment]
Fixed! Thanks for your help @Hettomei 👌

**Comment by igrigorik** [comment]
\o/ ... awesome work. Thanks @Hettomei!
