### ISSUE TITLE
Slow database operation: add index?

### ISSUE THREAD

**Issue by igrigorik** [igrigorik/vimgolf#253]
Helpful suggestion from mLab...

![image](https://user-images.githubusercontent.com/10652/44170770-3718b880-a08d-11e8-853a-a81e0d17ee50.png)

/cc @Hettomei

**Comment by Hettomei** [comment]
> Slow database operation: add index?

I read that aggregator will need good index and we can just follow the 'explain' of mongodb.

Now we have to understand how to add index in rails
And then keep reading the logs to find all the recommended indexes
