### ISSUE TITLE
Real best score for "Simple, Practical, and Common"

### ISSUE THREAD

**Issue by sedm0784** [igrigorik/vimgolf#256]
I know the top 5 entries are faked by editing the temporary file, and the highest rated entry that I can see [also appears to cheat](http://www.vimgolf.com/challenges/55b18bbea9c2c30d04000001#5ad20432cf54c60f7a000001) by pasting from the system clipboard.

But there are 28 other entries that have scores in between these that I cannot see (because I don't want to copy the cheating entry). Are these all faked too? Is 22 actually the best score for this challenge?

**Comment by Hettomei** [comment]
Just do the cheat.

Then look at the solution

Then delete your entry.

All entries are saved. Only the best entry per player is displayed.

So after deleting your 'cheat', it comes back to your 'real' solution. (To delete, you have to click on 'edit comment')


Regarding 'cheats' there is like 10 moderators that can delete them. See on FAQ page. Try to ping them on twitter.

**Comment by Hettomei** [comment]
Remember it s not really cheat, just people trying to push vim/vimgolf yo the edge case to see what happen :)

**Comment by sedm0784** [comment]
Oh cool, I didn’t realise it saved all entries or even that you could delete them. Thanks!
