### ISSUE TITLE
Unwanted permissions asked during Twitter authentication

### ISSUE THREAD

**Issue by siddharthasahu** [igrigorik/vimgolf#259]
The Twitter authentication needs access to read my tweets and see who I follow. Is that deliberate?
I don't want to give those permission just to login and submit & review other submissions.

**Comment by igrigorik** [comment]
No, we should revisit the scope we request. I don't recall why I originally chose that scope, but if there is a more restrictive option that works, we should use that.

**Comment by siddharthasahu** [comment]
It might not be possible: https://stackoverflow.com/questions/8706170/does-twitter-use-any-sorts-of-permissions-for-their-oauth-api

It's also the case that my tweets and followers are public anyway. It just makes me uncomfortable when an authenticating app asks for more permissions than strictly necessary. I guess in this case it is fine. You still might want to revisit something like https://github.com/igrigorik/vimgolf/issues/119 sometime when you do have the time.

Thanks for the prompt response!
