### ISSUE TITLE
Esc on Mac OS produces <Esc><fd-61> with current gem version

### ISSUE THREAD

**Issue by seren** [igrigorik/vimgolf#268]
This has recently started happening with the latest vimgolf from rubygems: hitting `esc` or `ctrl-[` produces `<Esc><fd-61>` in the keystroke record. This makes it impossible to progress in the challenges.

Cloning the repo and running the code directly avoids this error, though submissions fail until you hack the version number to be the same as the gem version.

This may be the reason for the request of a new gem version in #267 .

**Comment by afreakk** [comment]
`<Esc><fd-61>` happens on linux aswell.

**Comment by grant7788** [comment]
Also happens on Linux, Ubuntu 16.04.6, Vim 8.1
Found out that if you press the next key soon enough, <fd-61> wont happen.

**Comment by fallwith** [comment]
I too have been having this issue with the currently published gem but not the current GitHub code.

Today I noticed that the `<fd-61>` phantom stroke still counts against my score locally but no longer appears in my submission on vimgolf.com. My local score was reported as `34` while the posted submission was listed as `33`.

Plus one from me for releasing what's currently in GitHub to rubygems.org...

Workaround until then to use the latest GitHub code:

```
gem uninstall vimgolf
git clone https://github.com/igrigorik/vimgolf.git
cd vimgolf
cd lib/vimgolf
gem build vimgolf.gemspec
gem install vimgolf-0.4.8.gem
```

**Comment by vegerot** [comment]
I think this key is "inserted" when you hold down `shift` too long.   If I am holding shift and thinking about my next move, it is inserted, but if I quickly press shift+key, it is not inserted.

**Comment by r4d1um** [comment]
Please fix this bug it's frustrating on macOS.

**Comment by lbkvu** [comment]
I still have the same problem on Linux. I cannot rank in the top because of this. Please fix!

**Comment by Hettomei** [comment]
Hi @lbkvu 
This workaround mays works for you : use docker

See http://www.vimgolf.com/about > Setup Tips & Tricks >

```
docker run --rm -it -e "key=[YOUR_VIMGOLF_KEY]" kramos/vimgolf [challenge ID]
```

Let me know if it fix your problem

**Comment by lbkvu** [comment]
Hi @Hettomei 

Thank you for your help. I tried it and `<fd-61>` disappeared

**Comment by filbranden** [comment]
I believe commit 3bf4116f786148bc49f23056a4fc363425d18cbb fixes this issue.

Regarding the Docker image (`kramos/vimgolf`) it ships with Vim 7.4 which is unfortunately insufficient for Vimgolf, as it's missing some features very useful for some challenges (such as the [`g CTRL-A`](https://vimhelp.org/change.txt.html#v_g_CTRL-A) visual mode command.)

I just pinged issue #267 again asking for a release, I think we ought to get one to get this issue finally addressed in the official release.

Cheers!
Filipe

**Comment by Hettomei** [comment]
Since v 0.4.9 is out, can we close this one ?

**Comment by seren** [comment]
Sure thing.
