### ISSUE TITLE
Twitter name doesn't get updated

### ISSUE THREAD

**Issue by miloszlakomy** [igrigorik/vimgolf#269]
Hello. I have updated my first and last name on Twitter: https://twitter.com/foobar01123 ,
but can't see them on Vimgolf: http://www.vimgolf.com/foobar01123

**Comment by filbranden** [comment]
Vimgolf will update your name information from Twitter *when you sign in using Twitter*, so if you sign out and back in it should update it. I see that right now both are in sync, so I believe you probably has done that since filing this issue... I'll go ahead and close the issue.
