### ISSUE TITLE
Non-Twitter Auth

### ISSUE THREAD

**Issue by jemmaissroff** [igrigorik/vimgolf#300]
I would love to use vimgolf but have absolutely no desire to have a Twitter account. Is vimgolf necessarily dependent on Twitter? Would it be possible to allow for other types of Auth?

I would be happy to look into implementing this if it's something y'all would be interested in too.

**Comment by Trewornan** [comment]
Thanks for opening this Jemma, I feel exactly the same. You'd think a bunch of presumably savvy computer users would know better than to have Twitter accounts.

**Comment by Hettomei** [comment]
Vimgolf use omniauth.

Omniauth works with plugin

Here is the doc to add omniauth github https://github.com/omniauth/omniauth-github

Feel free to open a pull request.

**Comment by Vlek** [comment]
Any work on this? I too would like to use vimgolf and I absolutely do not want a twitter.

**Comment by ic-768** [comment]
Would be great if this was implemented.
The twitter-only auth has deterred me from playing ever since I found out about vimgolf, as I don't want to sign up for a twitter account. 

The latest news around twitter might also be a good incentive on allowing different auth methods.

**Comment by sdedovic** [comment]
Want to bump this, especially with the uncertainty about twitter's future

**Comment by r4d1um** [comment]
I cannot even login anymore using my twitter account so a switch seems to be necessary.

**Comment by ant0sha** [comment]
> I cannot even login anymore using my twitter account so a switch seems to be necessary.

Just filed an issue #375 with not being able to log-in with Twitter account since 2023-04-29. Others seems to as well have that issue, according to this reddit post https://www.reddit.com/r/vim/comments/1351trf/vimgolf_cannot_signin_using_twitter_account/

**Comment by despotes** [comment]
> Vimgolf use omniauth.
> 
> Omniauth works with plugin
> 
> Here is the doc to add omniauth github https://github.com/omniauth/omniauth-github
> 
> Feel free to open a pull request.

I made Pull Request implementing the new OmniAuth authentication with Github #376 
I hope someone of the Maintainers or Contributors would take a look
