### ISSUE TITLE
Paste from clipboard

### ISSUE THREAD

**Issue by lotusirous** [igrigorik/vimgolf#305]
I can produce the result from any challenges with the lowest keystroke by pasting the result from clipboard 

For example the challenge: http://www.vimgolf.com/challenges/51ed21c65b7a9c0002000012

can be solved with the following keystroke which does not valid.

`o<C-R>*<Esc>ZZ`

**Comment by filbranden** [comment]
In [the about page](http://www.vimgolf.com/about), Rule `#8` is:

> Cheaters ***will be*** publicly ridiculed by fellow golfers :-)

So I guess that's working as expected? :smile: 

There are many ways to cheat really... But it's only fun when you play fair. Yeah blocking some low hanging fruit in cheating is maybe worth it, but there's a limit to how much can be done.

**Comment by lotusirous** [comment]
I got it. Thanks :)
