### ISSUE TITLE
Could not load webpages correctly

### ISSUE THREAD

**Issue by wuzirui** [igrigorik/vimgolf#309]
for most golf challenges, the browser gives   "We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly."

but I can open a few challenges(e.g. Inverting Lines), which seems strange to me

**Comment by Hettomei** [comment]
Hi.

It has been openned at #306 and the technical details are at #307 

If you have some knowledge in mongodb, please, come to help :D 

@wuzirui  Can we close this issue because of 'duplicate'

**Comment by wuzirui** [comment]
> Hi.
> 
> It has been openned at #306 and the technical details are at #307
> 
> If you have some knowledge in mongodb, please, come to help :D
> 
> @wuzirui Can we close this issue because of 'duplicate' ?
> 
> (Note : webpage works for challenge with less than 500 entries)

Sure, sorry about my mistake
