### ISSUE TITLE
Should show <C-End> and <C-Right> instead of their opposite

### ISSUE THREAD

**Issue by danilobellini** [igrigorik/vimgolf#352]
In my recent solution to the 9v0062e3e96a000000000226 challenge played with the Docker container (the current one, `hettomei/vimgolf@sha256:be79c58788d789129fcf4d87390dd4c61df9d9200d947acde4a7a00698731228`), I used `<C-End>` and `<C-Right>` in insert mode. However, the `Here are your keystrokes:` message before pushing it to the web shows `<C-Home>` and `<C-Left>` instead (and, since I've pushed it, the web site is also showing the solution with these misleading replacement, that's actually how I noticed this). I'm not sure what happened, but the shown sequence of keystrokes is misleading this way, showing the opposite of what I pressed while solving the challenge (I commented this on the solution).

**Comment by danilobellini** [comment]
Update: I just deleted the entry from there, and published it again using this Python client: https://pypi.org/project/vimgolf/0.4.3/

It uses the Vim in the local machine, the standard huge version from Arch Linux repository:

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 28 2022 16:22:51)
Compiled by Arch Linux
Huge version with GTK3 GUI.
```

That said, the bug seems to be related to the Vim version running in the Docker container, which is:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 21 2019 04:10:35)
Included patches: 1-197, 322, 377-378, 550, 649, 651, 703, 706-707
Extra patches: 8.1.1401, 8.1.1382, 8.1.1368, 8.1.1367, 8.1.1366, 8.1.1365, 8.1.1046, 8.1.0613, 8.1.0547, 8.1.0546, 8.1.0544, 8.1.0540, 8.1.0539, 8.1.0538, 8.1.0506, 8.1.0208,
 8.1.0206, 8.1.0205, 8.1.0189, 8.1.0177, 8.1.0067, 8.1.0066
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.
```

But I'll keep this issue since there might be other solutions from other people that might need to be fixed.

**Comment by Hettomei** [comment]
The docker is mine. I don't maintain it.

If anyone want to create another and create a push request to the FAQ page to change the docker link, I think it will be ok.
