### ISSUE TITLE
since ~2023-04-29 not able to log-in to www.vimgolf.com with twitter account: "The page you were looking for doesn't exist."

### ISSUE THREAD

**Issue by ant0sha** [igrigorik/vimgolf#375]
Don't know if it is the right place to report it, but this is my best try...

Last Saturday, 29th May, I recognized it is not possible to log-in to www.vimgolf.com using the twitter account. Error message shown in browser is:

> The page you were looking for doesn't exist.
> You may have mistyped the address or the page may have moved.

Firstly I assumed it only affects access from the mobile phone, because access from laptop with firefox was fine. Today after firefox restart the same error message started to be shown in the firefox on laptop.

After quick searching in the web, apparently that others have same issue as me, as it was reported by others on redit as well  3 days ago: https://www.reddit.com/r/vim/comments/1351trf/vimgolf_cannot_signin_using_twitter_account/

**Comment by ant0sha** [comment]
Actually access to the puzzles still work, seem that key provided in the beginning and saved with 'vimgolf setup ..key ..' remains valid, is there may be some possibility to use that key to view available solutions with my current score?

**Comment by stablestud** [comment]
Same error starts to pop up for me aswell.
Propably Twitter has changed the external auth procedure.
Seems to be something for the site hoster, @igrigorik would you be so kind and ping the hoster or the person best knowledgeable about this, as the site is now unfortunately almost useless... :disappointed:
VimGolf is a value piece to kickstart Vim, would be sad if its not accessible anymore...

**Comment by despotes** [comment]
I opened a Pull Request #376  to add a new OAuth Sign In with Github, hope the Maintainers will check it out soon.

**Comment by joachimnielandt** [comment]
After clicking login with github, I get a 404 on the following: https://github.com/login/oauth/authorize?client_id=dev&redirect_uri=https%3A%2F%2Fwww.vimgolf.com%2Fauth%2Fgithub%2Fcallback&response_type=code&state=b373fdxxxxdedf68f39bxxxxa3283dadbe4xxxx44a1

**Comment by igrigorik** [comment]
Should be fixed. Thanks for the patience!
