### ISSUE TITLE
Option to use without Twitter

### ISSUE THREAD

**Issue by marek22k** [igrigorik/vimgolf#380]
Hello,

Currently you can only participate or register if you have a Twitter account. However, I deleted my Twitter account some time ago and am now in Fediverse. Is there an alternative way to register?

**Comment by anakojm** [comment]
It seems that using a github account has  been implemented with #376 and it is now just a matter of updating https://www.vimgolf.com/.
I believe this does not close this issue though, because some people do not/do not wish to have github or twitter.

**Comment by Hettomei** [comment]
Also Linked to #9  #300 

Since #376  is merged, I ask here : 

@igrigorik  or maybe @filbranden have you the time to update the environment variable as stated here : https://github.com/igrigorik/vimgolf/pull/376#issuecomment-1543524352 ?

**Comment by igrigorik** [comment]
Should be live now!
