### ISSUE TITLE
Installation Failure 

### ISSUE THREAD

**Issue by tncargil** [igrigorik/vimgolf#388]
Attempting to install  vimgolf on arch with commands:
pacman -S Ruby
gem install vimgolf 
I am getting this error: 
![image](https://github.com/user-attachments/assets/aadc94f2-435c-4d8e-9188-3317a68e2a36)

**Comment by filbranden** [comment]
Doesn't look like a problem with vimgolf itself, more like a problem with your Ruby install, as far as I can tell `erb` is a standard module of Ruby so it should have been included with your setup. Maybe try to reinstall Ruby?

**Comment by tncargil** [comment]
Removing and reinstalling did not resolve the issue. For more context here is the version of ruby I am using 
~> ruby -v
ruby 3.2.4 (2024-04-23 revision af471c0e01) [x86_64-linux]

**Comment by tncargil** [comment]
I found a solution running gem install erb resolved my missing erb module
