### ISSUE TITLE
Collapse identical solutions

### ISSUE THREAD

**Issue by lionelyoung** [igrigorik/vimgolf#39]
In the solution preview, there are many identical solutions, but I'd like to study the non-unique solutions.

Another way of presenting solutions is this: all identical solutions get creditted to the first one who submitted it.  Under the solution box, you could perhaps have text that says: "55 more identical solutions from..."

**Comment by deft-code** [comment]
This feature never landed. Can we reopen and try again. Vimgolf would be more fun to browse if each page listed unique solutions rather than a list of duplicates.

I would go as far a suggesting that only unique solutions get ranked, but visually collapsing them would be sufficient.

**Comment by Hettomei** [comment]
Can anybody draw an example of what you think the page should be  ?
