### ISSUE TITLE
Diff says entry does not match, but looks correct.

### ISSUE THREAD

**Issue by bradly** [igrigorik/vimgolf#63]
Is this a line ending issue? Could this be noted in the diff?

```
`  vimgolf put 4d2f0fe063b08b08b0000019`
`  Launching VimGolf session for challenge: 4d2f0fe063b08b08b0000019`
`  Uh oh, looks like your entry does not match the desired output:`
`  ##################################################`
`  15c15`
`  < }`
`  ---`
`  > }`
```

**Comment by peterjeliot** [comment]
Is there any update on this? I'm failing some with no idea why.

**Comment by peterjeliot** [comment]
Is there any update on this? I'm still failing a bunch and am not sure why. It's a whitespace issue according to the diff, but I can't tell what whitespace it wants.
