### ISSUE TITLE
how to submit a solution ? 

### ISSUE THREAD

**Issue by RusAlex** [igrigorik/vimgolf#76]
very tired, maybe missed something ?

**Comment by zackster** [comment]
To submit the solution, just save the file `:wq`

**Comment by keshav-c** [comment]
`<Esc>:wq` counts 4 entries towards the challenge

**Comment by stoyandimov** [comment]
> `<Esc>:wq` counts 4 entries towards the challenge

How would you exit without `<Esc>:wq<CR>`

**Comment by S-Bartfast** [comment]
Does "ZZ" work for you?

**Comment by sedm0784** [comment]
> Is there any reason a "Project Euler style" entry box isn't available to simply paste solutions into? I now understand your whole ethos is compliantly different but if it's not too hard to implement a simple entry box would make things a lot more accessible Windows/casual Vim users.

I'm not a contributor to this project, but I think the reason is just that it would be difficult to do. There's some discussion of some of the issues involved in issue #226.
