### ISSUE TITLE
non-twitter auth sources?

### ISSUE THREAD

**Issue by rnesius** [igrigorik/vimgolf#84]
I nuked my twitter account several years ago - I've no desire to have an identity there.  I don't see another way to establish an identity on the vimgolf site though - any plans to support OpenID auths or anything?  Sorry if this is the wrong place to ask.

**Comment by m42e** [comment]
+1 What about github ?

**Comment by beatgutzwiller** [comment]
+1 for Github

**Comment by Hettomei** [comment]
First it needs to work on development env on localhost.

**Comment by Joe-mcgee** [comment]
+1 for options, it is a matter of [ethics](https://en.wikipedia.org/wiki/Technological_determinism)

**Comment by synthead** [comment]
Yeah... not too into the idea of Twitter for auth, either.

**Comment by gloryVine** [comment]
Requiring a Twitter account is crazy. What the hell?

**Comment by Hettomei** [comment]
@gloryVine this is not a way to request a feature to an open source project.
Also you can still submit a pull request.

**Comment by gloryVine** [comment]
> @gloryVine this is not a way to request a feature to an open source project.
> Also you can still submit a pull request.

It is exactly the correct response. By clicking on 'sign in with twitter' I am told that:
This application will be able to:
See Tweets from your timeline (including protected Tweets) as well as your Lists and collections.
See your Twitter profile information and account settings.
See accounts you follow, mute, and block.

This is crazy for a project supposed to help me improve my vim skills. I've never seen anything like that before. It's unethical.

**Comment by Hettomei** [comment]
Please be more comprehensive.
It is not the way you think it is.
Take a fun project. Implement a quick auth. Why not twitter. Then you don't take time to refine it. That's it. No more.
So now, please send a PR that reduce twitter access or add any better auth.

**Comment by beatgutzwiller** [comment]
> > @gloryVine this is not a way to request a feature to an open source project.
> 
> It is exactly the correct way. By clicking on 'sign in with twitter' I am told that:
> This application will be able to:
> See Tweets from your timeline (including protected Tweets) as well as your Lists and collections.
> See your Twitter profile information and account settings.
> See accounts you follow, mute, and block.
> 
> This is crazy for a project supposed to help me improve my vim skills, I've never seen anything like that before.

While I absolutely agree with your point, this seems a bit like an overstatement. Never seen anything like that? Well have you ever installed a phone app? Or do you have a SmartTV, SmartHome or Smartspeaker? Well then you have seen worse.

Yes it is strange to have twitter as an auth. while the target audience is not the typical twitter user. But the biggest problem is, that just a lot of people don't have twitter, and it would be crazy to make an account just for that. 
There is likely no evil reason behind that....

**Comment by gloryVine** [comment]
> While I absolutely agree with your point, this seems a bit like an overstatement. Never seen anything like that? Well have you ever installed a phone app? Or do you have a SmartTV, SmartHome or Smartspeaker? Well then you have seen worse.

I have an iPhone, and do not install apps which ask for any access beyond that needed to do what I installed them for. (E.g., a scan-app doesn't get access to my contacts, or to draw the analogy, an app for learning key bindings for a text editor wouldn't get access to my social media posts.)
Also no, I do not have either of the other three.

> Yes it is strange to have twitter as an auth. while the target audience is not the typical twitter user. But the biggest problem is, that just a lot of people don't have twitter, and it would be crazy to make an account just for that.

Both are huge problems: 1. That a program with such a basic functionality would even ask for accessing personal information (including protected tweets), and that 2a. It would require people to create an account with a third party with more than questionable data ethics, and then 2b. additionally request access to the data on that account.
Neither of those is acceptable.

And this is also what I meant by having 'never seen anything like that before'. I have not. I am used to at least having the option of signing in via e-mail.
