### ISSUE TITLE
vimgolf put ... "Vim did not exit properly"

### ISSUE THREAD

**Issue by DestyNova** [igrigorik/vimgolf#88]
Vimgolf for some reason fails to start vim in the first place, it seems?

;;;;
C:\U\O\Documents\code> vimgolf put 4f9840d6cb724b0001000010
Downloading Vimgolf challenge: 4f9840d6cb724b0001000010
Launching VimGolf session for challenge: 4f9840d6cb724b0001000010
["C:/Ruby192/lib/ruby/gems/1.9.1/gems/vimgolf-0.4.1/lib/vimgolf/cli.rb:79:in `put'", "vim -Z -n --noplugin -i NONE +0 -u \"C:/Users/Omf/.vimgolf/put/4f9840d6cb724b0001000010.golfrc\" -W \"C:/Users/Omf/.vimgolf/put/4f9840d6cb724b0001000010.log\" \"C:/Users/Omf/.vimgolf/put/4f9840d6cb724b0001000010.work.rb\""]
          Uh oh, Vim did not exit properly. If the problem persists, please
          report the error on github.com/igrigorik/vimgolf
;;;;

I'm not sure what's going on. Calling vim (and diff) from the same command prompt, with the same arguments, seems to work fine.

;;;;
C:\U\O\Documents\code> vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct 27 2010 17:51:38)
MS-Windows 32-bit console version
Included patches: 1-46
;;;;

**Comment by Erhannis** [comment]
On mine (Ubuntu), I had to 1. add `alias vim='vi'` to my ~/.bashrc, and 2. `apt install vim-gui-common`.
